export const products = [
    "SINGLE JERSEY CIRCULAR KNITTING MACHINES",
    "DOUBLE JERSEY CIRCULAR KNITTING MACHINES",
    "COMPUTERIZED/ELECTRONIC JACQUARD CIRCULAR KNITTING MACHINES",
    "CIRCULAR KNITTING MACHINES SPARE PARTS"
]